CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=n
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# Explicitly enable LVGL Label objects
CONFIG_LV_USE_LABEL=y

CONFIG_SENSOR=y
CONFIG_MPU6050=y

# USB Serial UART Logging
CONFIG_ZMK_USB_LOGGING=y